module OpenTopo
  class Client
    @request: untyped

    API_KEY_NAME: "OPEN_TOPOGRAPHY_API_KEY"

    def initialize: (?untyped? api_key) -> void

    def globaldem: (south: untyped, north: untyped, west: untyped, east: untyped, ?demtype: ::Symbol, ?output_format: ::Symbol) -> untyped

    def usgsdem: (south: untyped, north: untyped, west: untyped, east: untyped, ?dataset_name: ::Symbol, ?output_format: ::Symbol) -> untyped

    def elevation: (long: untyped, lat: untyped, ?dataset: ::Symbol) -> untyped

    def catalog: (?west: untyped?, ?south: untyped?, ?east: untyped?, ?north: untyped?, ?polygon: untyped?) -> untyped

    private

    attr_reader request: untyped
  end
end
